### PR TITLE
[wpmlcore-5169] Created WPML_VC_Website_Builder_Data_Settings

### PR DESCRIPTION
**Pull request by adrianosferreira**

### CODE REVIEW

**Comment by grey-rsi** [comment]
@adrianosferreira looks good +1

**Review by ghost — APPROVED** [review]
@adrianosferreira looks good +1

**Comment by adrianosferreira** [comment]
@BruceOnTheGo please review it.

**Review by brucepearson — APPROVED** [review]
@adrianosferreira This looks ok

**Pull request merged**
